name: TTag CI

on: [pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18.x'
                  cache: 'npm'
            - run: npm install
            - name: TS check
              run: npm run ts-check
            - name: Test
              run: npm run test
            - name: Prettier check
              run: npm run prettier-check
            - name: Linter check
              run: npm run lint
